In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("study_data.csv")

In [30]:
print(df)

   Study Hours  Practice Tests  Score
0            2               1     60
1            3               2     65
2            4               2     70
3            5               3     75
4            6               3     80


In [31]:
X = np.ones(5).reshape(5,1) 

In [32]:
print(X)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [33]:
df_values = df[['Study Hours', 'Practice Tests']].to_numpy()

In [34]:
X = np.hstack((X, df_values))

In [35]:
print(X)

[[1. 2. 1.]
 [1. 3. 2.]
 [1. 4. 2.]
 [1. 5. 3.]
 [1. 6. 3.]]


In [36]:
Y = df['Score']

In [37]:
Y

0    60
1    65
2    70
3    75
4    80
Name: Score, dtype: int64

In [38]:
def calculate_B(X, Y):
  
    try:
        XT_X = X.T @ X
        XT_X_inv = np.linalg.inv(XT_X) 
        XT_Y = X.T @ Y 
        B = XT_X_inv @ XT_Y
        return B
    except np.linalg.LinAlgError:
        print("Error: X^T * X is singular (non-invertible). Cannot calculate B.")
        return None


B = calculate_B(X, Y)

In [39]:
print(B)

[ 5.00000000e+01  5.00000000e+00 -4.54747351e-13]
